# This profiles.yml file is provide as an example for running locally. 
optimism_dbt_models:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'duckdb/optimism_dbt_models.duckdb'
      extensions:
        - httpfs
        - parquet


clickhouse_goldsky:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('CLICKHOUSE_GOLDSKY_DBT_HOST') }}"
      port: "{{ env_var('CLICKHOUSE_GOLDSKY_DBT_PORT') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_GOLDSKY_DBT_USER') }}"
      password: "{{ env_var('CLICKHOUSE_GOLDSKY_DBT_PASSWORD') }}"
      secure: True