# This profiles.yml file is provide as an example for running locally. 
optimism_dbt_models:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'duckdb/optimism_dbt_models.duckdb'
      extensions:
        - httpfs
        - parquet


clickhouse_goldsky:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: https://pdmv9lhojy.us-west-2.aws.clickhouse.cloud
      port: 8443
      user: "{{ env_var('CLICKHOUSE_GOLDSKY_DBT_USER') }}"
      password: "{{ env_var('CLICKHOUSE_GOLDSKY_DBT_PASSWORD') }}"
      secure: False