/* AUTO-GENERATED FILE. DO NOT CHANGE. This file was autogenerated by the generate_sources command. */

{{ config(materialized='view') }}

SELECT
    chain,
    network,
    chain_id,
    formatDateTime(block_timestamp, '%Y-%m-%d') AS dt,
    block_timestamp,
    accurateCast(block_number, 'Int64') AS block_number,
    cast(block_hash, 'String') AS block_hash,
    cast(transaction_hash, 'String') AS transaction_hash,
    accurateCast(transaction_index, 'Int64') AS transaction_index,
    cast(from_address, 'String') AS from_address,
    cast(to_address, 'String') AS to_address,
    accurateCastOrNull(value, 'Int64') AS value_64,
    cast(value, 'String') AS value_lossless,
    input,
    output,
    cast(trace_type, 'String') AS trace_type,
    cast(call_type, 'String') AS call_type,
    cast(reward_type, 'String') AS reward_type,
    accurateCast(gas, 'Int64') AS gas,
    accurateCast(gas_used, 'Int64') AS gas_used,
    accurateCast(subtraces, 'Int64') AS subtraces,
    cast(trace_address, 'String') AS trace_address,
    cast(error, 'String') AS error,
    accurateCast(status, 'Int64') AS status
FROM {{ source("goldsky_pipelines", "traces") }}