/* AUTO-GENERATED FILE. DO NOT CHANGE. This file was autogenerated by the generate_sources command. */

{{ config(materialized='view') }}

SELECT
    chain,
    network,
    chain_id,
    formatDateTime(block_timestamp, '%Y-%m-%d') AS dt,
    block_timestamp,
    accurateCast(block_number, 'Int64') AS block_number,
    cast(block_hash, 'String') AS block_hash,
    cast(hash, 'String') AS hash,
    accurateCast(nonce, 'Int64') AS nonce,
    accurateCast(transaction_index, 'Int64') AS transaction_index,
    cast(from_address, 'String') AS from_address,
    cast(to_address, 'String') AS to_address,
    accurateCastOrNull(value, 'Int64') AS value_64,
    cast(value, 'String') AS value_lossless,
    accurateCast(gas, 'Int64') AS gas,
    accurateCast(gas_price, 'Int64') AS gas_price,
    input,
    accurateCast(transaction_type, 'Int32') AS transaction_type,
    accurateCast(max_fee_per_gas, 'Int64') AS max_fee_per_gas,
    accurateCast(max_priority_fee_per_gas, 'Int64') AS max_priority_fee_per_gas,
    accurateCast(receipt_cumulative_gas_used, 'Int64') AS receipt_cumulative_gas_used,
    accurateCast(receipt_gas_used, 'Int64') AS receipt_gas_used,
    receipt_contract_address,
    accurateCast(receipt_status, 'Int32') AS receipt_status,
    accurateCast(receipt_effective_gas_price, 'Int64') AS receipt_effective_gas_price,
    accurateCast(receipt_l1_gas_price, 'Nullable(Int64)') AS receipt_l1_gas_price,
    accurateCast(receipt_l1_gas_used, 'Nullable(Int64)') AS receipt_l1_gas_used,
    accurateCast(receipt_l1_fee, 'Nullable(Int64)') receipt_l1_fee,
    receipt_l1_fee_scalar,
    accurateCast(receipt_l1_blob_base_fee, 'Nullable(Int64)') AS receipt_l1_blob_base_fee,
    accurateCast(receipt_l1_blob_base_fee_scalar, 'Nullable(Int64)') AS receipt_l1_blob_base_fee_scalar,
    accurateCast(receipt_l1_base_fee_scalar, 'Nullable(Int64)') AS receipt_l1_base_fee_scalar
FROM {{ source("goldsky_pipelines", "transactions") }}