/* AUTO-GENERATED FILE. DO NOT CHANGE. This file was autogenerated by the generate_sources command. */

{{ config(materialized='view') }}

SELECT
    chain,
    network,
    chain_id,
    block_timestamp,
    accurateCast(block_number, 'Int64') AS block_number,
    cast(block_hash, 'String') AS block_hash,
    cast(transaction_hash, 'String') AS transaction_hash,
    accurateCast(transaction_index, 'Int64') AS transaction_index,
    accurateCast(log_index, 'Int64') AS log_index,
    cast(address, 'String') AS address,
    cast(topics, 'String') AS topics,
    cast(data, 'String') AS data,
    splitByChar(',', topics)[1] as topic0,
    arraySlice(splitByChar(',', topics), 2) as indexed_args
FROM {{ source("goldsky_pipelines", "logs") }}