/* AUTO-GENERATED FILE. DO NOT CHANGE. This file was autogenerated by the generate_sources command. */

{{ config(materialized='view') }}

SELECT
    timestamp,
    number,
    hash,
    parent_hash,
    nonce,
    sha3_uncles,
    logs_bloom,
    transactions_root,
    state_root,
    receipts_root,
    withdrawals_root,
    miner,
    difficulty,
    total_difficulty,
    size,
    base_fee_per_gas,
    gas_used,
    gas_limit,
    extra_data,
    transaction_count
FROM {{ source("superchain_goldsky", "op_blocks") }}