CREATE TABLE IF NOT EXISTS blockbatch.contract_creation__create_traces_v1
(
    `chain` String,
    `dt` Date,
    `network` String,
    `chain_id` Int32,
    `block_timestamp` DateTime CODEC(Delta(4), ZSTD(1)),
    `block_number` UInt64 CODEC(Delta(4), ZSTD(1)),
    `block_hash` FixedString(66),
    `transaction_hash` FixedString(66),
    `transaction_index` Int64,
    `tr_from_address` FixedString(42),
    `tx_from_address` FixedString(42),
    `contract_address` FixedString(42),
    `tx_to_address` FixedString(42),
    `value` UInt256,
    `code` String,
    `output` String,
    `trace_type` String,
    `call_type` String,
    `reward_type` String,
    `gas` Int64,
    `gas_used` Int64,
    `subtraces` Int64,
    `trace_address` String,
    `error` String,
    `status` Int64,
    `tx_method_id` String,
    `code_bytelength` UInt64,
    INDEX dt_idx dt TYPE minmax GRANULARITY 1,
    INDEX block_timestamp_idx block_timestamp TYPE minmax GRANULARITY 1,
)
ENGINE = ReplacingMergeTree
ORDER BY (chain, dt, network, chain_id, block_number, transaction_hash, transaction_index, trace_address)