import json
import os

import polars as pl

from op_analytics.cli.subcommands.pulls.defillama.dexs.protocols import get_protocols_df


def test_protocols_df_full_response():
    with open(
        os.path.join(os.path.dirname(__file__), "mockdata/dexs_daily_volume_summary_response.json"),
        "r",
    ) as fobj:
        data = json.load(fobj)

    df = get_protocols_df(data)

    assert len(df) == 634

    assert df.schema == {
        "defillamaId": pl.String,
        "name": pl.String,
        "displayName": pl.String,
        "module": pl.String,
        "category": pl.String,
        "logo": pl.String,
        "chains": pl.List(pl.String),
        "protocolType": pl.String,
        "methodologyURL": pl.String,
        "methodology": pl.List(pl.Struct({"key": pl.String, "value": pl.String})),
        "latestFetchIsOk": pl.Boolean,
        "slug": pl.String,
        "id": pl.String,
        "parentProtocol": pl.String,
        "total24h": pl.Int64,
        "total48hto24h": pl.Int64,
        "total7d": pl.Int64,
        "total14dto7d": pl.Int64,
        "total60dto30d": pl.Int64,
        "total30d": pl.Int64,
        "total1y": pl.Int64,
        "totalAllTime": pl.Float64,
        "average1y": pl.Float64,
        "change_1d": pl.Float64,
        "change_7d": pl.Float64,
        "change_1m": pl.Float64,
        "change_7dover7d": pl.Float64,
        "change_30dover30d": pl.Float64,
        "breakdown24h": pl.List(
            pl.Struct({"chain": pl.String, "name": pl.String, "value": pl.Int64})
        ),
    }

    actual = df.head().to_dicts()
    assert actual == [
        {
            "defillamaId": "3",
            "name": "Curve DEX",
            "displayName": "Curve DEX",
            "module": "curve",
            "category": "Dexes",
            "logo": "https://icons.llamao.fi/icons/protocols/curve.png",
            "chains": [
                "Ethereum",
                "Polygon",
                "Fantom",
                "Arbitrum",
                "Avalanche",
                "Optimism",
                "Gnosis",
                "Fraxtal",
            ],
            "protocolType": "protocol",
            "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/curve",
            "methodology": [
                {"key": "UserFees", "value": "Swap fees paid by users"},
                {"key": "Fees", "value": "Swap fees paid by users"},
                {
                    "key": "Revenue",
                    "value": "Percentage of swap fees going to treasury and/or token holders",
                },
                {"key": "ProtocolRevenue", "value": "Percentage of swap fees going to treasury"},
                {"key": "HoldersRevenue", "value": "Money going to governance token holders"},
                {"key": "SupplySideRevenue", "value": "Liquidity providers revenue"},
            ],
            "latestFetchIsOk": True,
            "slug": "curve-dex",
            "id": "3",
            "parentProtocol": "parent#curve-finance",
            "total24h": 236906167,
            "total48hto24h": 613825215,
            "total7d": 2870235279,
            "total14dto7d": 2675729662,
            "total60dto30d": 10254852024,
            "total30d": 13258504372,
            "total1y": 97633438522,
            "totalAllTime": 212836362700.0,
            "average1y": None,
            "change_1d": -61.4,
            "change_7d": -0.63,
            "change_1m": -43.76,
            "change_7dover7d": 7.27,
            "change_30dover30d": 29.29,
            "breakdown24h": [
                {"chain": "ethereum", "name": "Curve DEX", "value": 215235889},
                {"chain": "polygon", "name": "Curve DEX", "value": 4287598},
                {"chain": "fantom", "name": "Curve DEX", "value": 2299516},
                {"chain": "arbitrum", "name": "Curve DEX", "value": 7844747},
                {"chain": "avax", "name": "Curve DEX", "value": 409778},
                {"chain": "optimism", "name": "Curve DEX", "value": 2503405},
                {"chain": "xdai", "name": "Curve DEX", "value": 2193604},
                {"chain": "fraxtal", "name": "Curve DEX", "value": 2131630},
            ],
        },
        {
            "defillamaId": "116",
            "name": "Balancer V1",
            "displayName": "Balancer V1",
            "module": "balancer",
            "category": "Dexes",
            "logo": "https://icons.llamao.fi/icons/protocols/balancer-v1.png",
            "chains": ["Ethereum"],
            "protocolType": "protocol",
            "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/balancer",
            "methodology": [
                {"key": "UserFees", "value": "Swap fees paid by users"},
                {"key": "Fees", "value": "Swap fees paid by users"},
                {
                    "key": "Revenue",
                    "value": "Percentage of swap fees going to treasury and/or token holders",
                },
                {"key": "ProtocolRevenue", "value": "Percentage of swap fees going to treasury"},
                {"key": "HoldersRevenue", "value": "Money going to governance token holders"},
                {"key": "SupplySideRevenue", "value": "Liquidity providers revenue"},
            ],
            "latestFetchIsOk": True,
            "slug": "balancer-v1",
            "id": "116",
            "parentProtocol": "parent#balancer",
            "total24h": 182633,
            "total48hto24h": 277532,
            "total7d": 1802722,
            "total14dto7d": 2378778,
            "total60dto30d": -45231866,
            "total30d": 12647884,
            "total1y": 240589195,
            "totalAllTime": 29711848029.0,
            "average1y": None,
            "change_1d": -34.19,
            "change_7d": -51.54,
            "change_1m": -64.59,
            "change_7dover7d": -24.22,
            "change_30dover30d": -127.96,
            "breakdown24h": [{"chain": "ethereum", "name": "Balancer V1", "value": 182633}],
        },
        {
            "defillamaId": "119",
            "name": "SushiSwap",
            "displayName": "SushiSwap",
            "module": "sushiswap",
            "category": "Dexes",
            "logo": "https://icons.llamao.fi/icons/protocols/sushiswap.png",
            "chains": [
                "Ethereum",
                "BSC",
                "Polygon",
                "Arbitrum",
                "Avalanche",
                "Harmony",
                "Fuse",
                "CORE",
                "Blast",
                "Fantom",
            ],
            "protocolType": "protocol",
            "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/sushiswap",
            "methodology": [
                {"key": "UserFees", "value": "Users pay a 0.3% fee on each trade"},
                {"key": "Fees", "value": "SushiSwap charges a flat 0.3% fee"},
                {"key": "Revenue", "value": "A 0.05% of each trade goes to treasury"},
                {"key": "ProtocolRevenue", "value": "Treasury receives a share of the fees"},
                {"key": "HoldersRevenue", "value": "None"},
                {
                    "key": "SupplySideRevenue",
                    "value": "Liquidity providers get 5/6 of all trades in their pools",
                },
            ],
            "latestFetchIsOk": True,
            "slug": "sushiswap",
            "id": "119",
            "parentProtocol": "parent#sushi",
            "total24h": 10953194,
            "total48hto24h": 12698470,
            "total7d": 65594547,
            "total14dto7d": 68510821,
            "total60dto30d": 445661670,
            "total30d": 358555344,
            "total1y": 5381091380,
            "totalAllTime": 956902562.0,
            "average1y": None,
            "change_1d": -13.74,
            "change_7d": -200.53,
            "change_1m": -74.27,
            "change_7dover7d": -4.26,
            "change_30dover30d": -19.55,
            "breakdown24h": [
                {"chain": "arbitrum", "name": "SushiSwap", "value": 1138326},
                {"chain": "avax", "name": "SushiSwap", "value": 1231},
                {"chain": "blast", "name": "SushiSwap", "value": 0},
                {"chain": "bsc", "name": "SushiSwap", "value": 9072},
                {"chain": "core", "name": "SushiSwap", "value": 0},
                {"chain": "ethereum", "name": "SushiSwap", "value": 8392718},
                {"chain": "fantom", "name": "SushiSwap", "value": 0},
                {"chain": "fuse", "name": "SushiSwap", "value": 167},
                {"chain": "polygon", "name": "SushiSwap", "value": 1262939},
                {"chain": "harmony", "name": "SushiSwap", "value": 148741},
            ],
        },
        {
            "defillamaId": "127",
            "name": "KyberSwap Classic",
            "displayName": "KyberSwap - Classic",
            "module": "kyberswap",
            "category": "Dexes",
            "logo": "https://icons.llamao.fi/icons/protocols/kyberswap-classic.png",
            "chains": [
                "Optimism",
                "Arbitrum",
                "Fantom",
                "Avalanche",
                "BSC",
                "Polygon",
                "Ethereum",
                "ZKsync Era",
                "Linea",
                "Scroll",
            ],
            "protocolType": "protocol",
            "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/kyberswap",
            "methodology": [
                {"key": "UserFees", "value": "Swap fees paid by users"},
                {"key": "Fees", "value": "Swap fees paid by users"},
                {
                    "key": "Revenue",
                    "value": "Percentage of swap fees going to treasury and/or token holders",
                },
                {"key": "ProtocolRevenue", "value": "Percentage of swap fees going to treasury"},
                {"key": "HoldersRevenue", "value": "Money going to governance token holders"},
                {"key": "SupplySideRevenue", "value": "Liquidity providers revenue"},
            ],
            "latestFetchIsOk": True,
            "slug": "kyberswap-classic",
            "id": "127",
            "parentProtocol": "parent#kyberswap",
            "total24h": 0,
            "total48hto24h": 0,
            "total7d": None,
            "total14dto7d": None,
            "total60dto30d": None,
            "total30d": None,
            "total1y": 16604871,
            "totalAllTime": 128728.0,
            "average1y": None,
            "change_1d": None,
            "change_7d": None,
            "change_1m": None,
            "change_7dover7d": None,
            "change_30dover30d": None,
            "breakdown24h": None,
        },
        {
            "defillamaId": "133",
            "name": "Shell Protocol",
            "displayName": "Shell Protocol",
            "module": "shell-protocol",
            "category": "Dexes",
            "logo": "https://icons.llamao.fi/icons/protocols/shell-protocol.jpg",
            "chains": ["Arbitrum"],
            "protocolType": "protocol",
            "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/shell-protocol",
            "methodology": [
                {"key": "UserFees", "value": "Swap fees paid by users"},
                {"key": "Fees", "value": "Swap fees paid by users"},
                {
                    "key": "Revenue",
                    "value": "Percentage of swap fees going to treasury and/or token holders",
                },
                {"key": "ProtocolRevenue", "value": "Percentage of swap fees going to treasury"},
                {"key": "HoldersRevenue", "value": "Money going to governance token holders"},
                {"key": "SupplySideRevenue", "value": "Liquidity providers revenue"},
            ],
            "latestFetchIsOk": True,
            "slug": "shell-protocol",
            "id": "133",
            "parentProtocol": None,
            "total24h": 0,
            "total48hto24h": 0,
            "total7d": None,
            "total14dto7d": None,
            "total60dto30d": 880726,
            "total30d": None,
            "total1y": 15466606,
            "totalAllTime": 101974579.0,
            "average1y": None,
            "change_1d": None,
            "change_7d": None,
            "change_1m": None,
            "change_7dover7d": None,
            "change_30dover30d": None,
            "breakdown24h": None,
        },
    ]


def test_breakdown24h():
    mock_response = {
        "protocols": [
            {
                "total24h": 400688463,
                "total48hto24h": 363047289,
                "total7d": 3632338610,
                "total14dto7d": 3303808860,
                "total60dto30d": 26678113925,
                "total30d": 19781592318,
                "total1y": 180577721770,
                "totalAllTime": 207992316157,
                "average1y": None,
                "change_1d": 10.37,
                "change_7d": 9.56,
                "change_1m": -55.8,
                "change_7dover7d": 9.94,
                "change_30dover30d": -25.85,
                "breakdown24h": {"solana": {"Orca": 395260883}, "eclipse": {"Orca": 5427580}},
                "defillamaId": "283",
                "name": "Orca",
                "displayName": "Orca",
                "module": "orca",
                "category": "Dexes",
                "logo": "https://icons.llamao.fi/icons/protocols/orca.jpg",
                "chains": ["Solana", "Eclipse"],
                "protocolType": "protocol",
                "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/orca",
                "methodology": {
                    "UserFees": "Swap fees paid by users",
                    "Fees": "Swap fees paid by users",
                    "Revenue": "Percentage of swap fees going to treasury and/or token holders",
                    "ProtocolRevenue": "Percentage of swap fees going to treasury",
                    "HoldersRevenue": "Money going to governance token holders",
                    "SupplySideRevenue": "Liquidity providers revenue",
                },
                "latestFetchIsOk": True,
                "slug": "orca",
                "id": "283",
            }
        ]
    }

    df = get_protocols_df(mock_response)
    actual = df.to_dicts()
    assert actual == [
        {
            "defillamaId": "283",
            "name": "Orca",
            "displayName": "Orca",
            "module": "orca",
            "category": "Dexes",
            "logo": "https://icons.llamao.fi/icons/protocols/orca.jpg",
            "chains": ["Solana", "Eclipse"],
            "protocolType": "protocol",
            "methodologyURL": "https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/orca",
            "methodology": [
                {"key": "UserFees", "value": "Swap fees paid by users"},
                {"key": "Fees", "value": "Swap fees paid by users"},
                {
                    "key": "Revenue",
                    "value": "Percentage of swap fees going to treasury and/or token holders",
                },
                {"key": "ProtocolRevenue", "value": "Percentage of swap fees going to treasury"},
                {"key": "HoldersRevenue", "value": "Money going to governance token holders"},
                {"key": "SupplySideRevenue", "value": "Liquidity providers revenue"},
            ],
            "latestFetchIsOk": True,
            "slug": "orca",
            "id": "283",
            "parentProtocol": None,
            "total24h": 400688463,
            "total48hto24h": 363047289,
            "total7d": 3632338610,
            "total14dto7d": 3303808860,
            "total60dto30d": 26678113925,
            "total30d": 19781592318,
            "total1y": 180577721770,
            "totalAllTime": 207992316157.0,
            "average1y": None,
            "change_1d": 10.37,
            "change_7d": 9.56,
            "change_1m": -55.8,
            "change_7dover7d": 9.94,
            "change_30dover30d": -25.85,
            "breakdown24h": [
                {"chain": "solana", "name": "Orca", "value": 395260883},
                {"chain": "eclipse", "name": "Orca", "value": 5427580},
            ],
        }
    ]
