import yaml
from yaml.representer import SafeRepresenter

from op_coreutils.logger import LOGGER

log = LOGGER.get_logger()


def custom_str_representer(dumper, data):
    """Pretty long strings.

    This custom representer forces using the | block style when dumping long strings to yaml.
    """
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return SafeRepresenter.represent_str(dumper, data)


yaml.add_representer(str, custom_str_representer)


def write_sources_yaml(path, dbt_sources: dict):
    with open(path, "w") as fobj:
        fobj.write(
            "### AUTO-GENERATED FILE. DO NOT CHANGE. This file was autogenerated by the generate_sources command."
        )

        yaml.dump(dbt_sources, fobj, sort_keys=False)
    log.info(f"Wrote dbt sources to {path}")
