# set parameters
LAST_N_DAYS = 30
INCENTIVE_PROGRAMS_ONLY = False

COL_NAMES_TO_INCLUDE = [
    "Status",
    "# OP Allocated",
    "App Name",
    "app_name",
    "app_name_join",
    "Source",
    "op_source",
    "category",
    "incentive_type",
    "txs_per_day",
    "num_addr_per_day",
    "gas_fee_eth_per_day",
    "gas_fee_usd_per_day",
    "l2_gas_used_per_day",
    "l1_gas_used_per_day",
    "txs_per_day_prev",
    "num_addr_per_day_prev",
    "gas_fee_eth_per_day_prev",
    "gas_fee_usd_per_day_prev",
    "l2_gas_used_per_day_prev",
    "l1_gas_used_per_day_prev",
    "num_addr_per_day_after",
    "gas_fee_eth_per_day_after",
    "gas_fee_usd_per_day_after",
    "l2_gas_used_per_day_after",
    "l1_gas_used_per_day_after",
    "incremental_txs_per_day",
    "incremental_addr_per_day",
    "incremental_gas_fee_eth_per_day",
    "incremental_gas_fee_usd_per_day",
    "incremental_l2_gas_used_per_day",
    "incremental_l1_gas_used_per_day",
    "incremental_addr_per_day_after",
    "incremental_gas_fee_eth_per_day_after",
    "incremental_gas_fee_usd_per_day_after",
    "incremental_l2_gas_used_per_day_after",
    "incremental_l1_gas_used_per_day_after",
    "cumul_last_price_net_dollar_flow",
    "net_op_deployed",
    "op_deployed"
]
