# -*- coding: utf-8 -*-
# set parameters
LAST_N_DAYS = 30

COL_NAMES_TO_INCLUDE = [
    "# OP Allocated",
    "app_name",
    "app_name_join",
    "op_source",
    "category",
    "incentive_type",
    "duration_days",
    "txs_per_day",
    "num_addr_per_day",
    "gas_fee_eth_per_day",
    "gas_fee_usd_per_day",
    "l2_gas_used_per_day",
    "l1_gas_used_per_day",
    "txs_per_day_prev",
    "num_addr_per_day_prev",
    "gas_fee_eth_per_day_prev",
    "gas_fee_usd_per_day_prev",
    "l2_gas_used_per_day_prev",
    "l1_gas_used_per_day_prev",
    "num_addr_per_day_after",
    "gas_fee_eth_per_day_after",
    "gas_fee_usd_per_day_after",
    "l2_gas_used_per_day_after",
    "l1_gas_used_per_day_after",
    "incremental_txs_per_day",
    "incremental_addr_per_day",
    "incremental_gas_fee_eth_per_day",
    "incremental_gas_fee_usd_per_day",
    "incremental_l2_gas_used_per_day",
    "incremental_l1_gas_used_per_day",
    "incremental_txs_per_day_after",
    "incremental_addr_per_day_after",
    "incremental_gas_fee_eth_per_day_after",
    "incremental_gas_fee_usd_per_day_after",
    "incremental_l2_gas_used_per_day_after",
    "incremental_l1_gas_used_per_day_after",
    "cumul_last_price_net_dollar_flow",
    "cumul_last_price_net_dollar_flow_at_program_end",
    "net_op_deployed",
    "op_deployed",
]
