apiVersion: batch/v1
kind: Job
metadata:
  name: op-analytics-4337-backfill-04
  namespace: op-analytics
  labels:
    app: op-analytics
    component: models-backfill

spec:
  ttlSecondsAfterFinished: null
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: op-analytics-service-account
      containers:
      - name: python-runner
        imagePullPolicy: Always
        image: ghcr.io/lithium323/op-analytics:v20250210.1
        command: ["tini", "-v", "--", "opdata"]
        args: ["chains", "aa_backfill_04"]
        env:
        - name: PLAIN_LOGS
          value: "true"
        - name: OPLABS_ENV
          value: "prod"
        - name: OPLABS_RUNTIME
          value: "k8s"
        - name: DUCKDB_DATADIR
          value: "/duckdbdata"
        - name: DUCKDB_MEMORY_LIMIT
          value: "6"
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 10Gi
            memory: 6Gi
          requests:
            cpu: 1
            ephemeral-storage: 10Gi
            memory: 4Gi
        volumeMounts:
        - mountPath: "/var/secrets"
          name: opanalyticsvault
        - mountPath: "/duckdbdata"
          name: duckdbdata
      restartPolicy: Never 
      volumes:
      - name: opanalyticsvault
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: op-analytics-secret-provider-class

      - name: duckdbdata
        emptyDir:
          sizeLimit: 100Gi
