apiVersion: batch/v1
kind: CronJob
metadata:
  name: op-analytics-models-daily
  namespace: op-analytics
  labels:
    app: op-analytics
    component: models-daily
spec:
  schedule: "50 * * * *"  # Runs every hour at minute 50
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: op-analytics-service-account
          containers:
          - name: python-runner
            imagePullPolicy: IfNotPresent
            image: ghcr.io/lithium323/op-analytics:v20250222.1
            command: ["tini", "-v", "--", "opdata"]
            args: ["chains", "noargs_intermediate"]
            env:
            - name: OPLABS_ENV
              value: "prod"
            - name: OPLABS_RUNTIME
              value: "k8s"
            - name: DUCKDB_DATADIR
              value: "/duckdbdata"
            resources:
              limits:
                cpu: 1
                ephemeral-storage: 10Gi
                memory: 12Gi
              requests:
                cpu: 1
                ephemeral-storage: 10Gi
                memory: 8Gi
            volumeMounts:
            - mountPath: "/var/secrets"
              name: opanalyticsvault
            - mountPath: "/duckdbdata"
              name: duckdbdata
          restartPolicy: OnFailure 
          volumes:
          - name: opanalyticsvault
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: op-analytics-secret-provider-class

          - name: duckdbdata
            emptyDir:
              sizeLimit: 100Gi
  successfulJobsHistoryLimit: 3  # Retains the last 3 successful jobs
  failedJobsHistoryLimit: 1      # Retains the last failed job