apiVersion: batch/v1
kind: Job
metadata:
  name: op-analytics-newchain-backfill
  namespace: op-analytics
  labels:
    app: op-analytics
    component: newchain-backfill

spec:
  completions: 16         # Number of indexes to process
  parallelism: 16          # How many pods can run in parallel
  completionMode: Indexed # This makes it an indexed job
  ttlSecondsAfterFinished: null
  backoffLimit: 3
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      serviceAccountName: op-analytics-service-account
      containers:
      - name: python-runner-newchain-backfill
        imagePullPolicy: Always
        image: ghcr.io/lithium323/op-analytics:v20250401.3
        command: ["tini", "-v", "--", "opdata"]
        args: ["chains", "newchain_backfill_models"]
        env:
        - name: PLAIN_LOGS
          value: "true"
        - name: OPLABS_ENV
          value: "prod"
        - name: OPLABS_RUNTIME
          value: "k8s"
        - name: DUCKDB_DATADIR
          value: "/duckdbdata"
        - name: DUCKDB_MEMORY_LIMIT
          value: "8"
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 10Gi
            memory: 6Gi
          requests:
            cpu: 1
            ephemeral-storage: 10Gi
            memory: 4Gi
        volumeMounts:
        - mountPath: "/var/secrets"
          name: opanalyticsvault
        - mountPath: "/duckdbdata"
          name: duckdbdata
      restartPolicy: Never 
      volumes:
      - name: opanalyticsvault
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: op-analytics-secret-provider-class
      - name: duckdbdata
        emptyDir:
          sizeLimit: 24Gi
