apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: op-analytics-secret-provider-class
  namespace: op-analytics
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/oplabs-tools-data/secrets/op-analytics-python-runner/versions/1"
        path: "op-analytics-vault.txt"