name: op-sepolia
version: 4
status: ACTIVE
resource_size: s
apiVersion: 3
sources:
  optimism_sepolia.raw_blocks:
    dataset_name: optimism_sepolia.raw_blocks
    version: 1.0.0
    type: dataset
    start_at: earliest
  optimism_sepolia.raw_logs:
    dataset_name: optimism_sepolia.raw_logs
    version: 1.0.0
    type: dataset
    start_at: earliest
  optimism_sepolia.transaction_receipts:
    dataset_name: optimism_sepolia.transaction_receipts
    version: 1.0.0
    type: dataset
    start_at: earliest
  optimism_sepolia.raw_traces:
    dataset_name: optimism_sepolia.raw_traces
    version: 1.0.0
    type: dataset
    start_at: earliest
transforms:
  optimism_sepolia_blocks:
    primary_key: id
    sql: |
      select
        *
        ,'op' as chain
        ,'sepolia' as network
        ,11155420 as chain_id
      from
        optimism_sepolia.raw_blocks
  optimism_sepolia_raw_logs:
    primary_key: id
    sql: |
      select
        *
        ,'op' as chain
        ,'sepolia' as network
        ,11155420 as chain_id
      from
        optimism_sepolia.raw_logs
  optimism_sepolia_raw_traces:
    primary_key: id
    sql: |
      select
        *
        ,'op' as chain
        ,'sepolia' as network
        ,11155420 as chain_id
      from
        optimism_sepolia.raw_traces
  optimism_sepolia_transactions:
    primary_key: id
    sql: |
      select
         *
        ,'op' as chain
        ,'sepolia' as network
        ,11155420 as chain_id
      from
        optimism_sepolia.transaction_receipts
sinks:
  clickhouse_optimism_sepolia.raw_blocks:
    type: clickhouse
    table: op_sepolia_blocks
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from optimism_sepolia.raw_blocks to optimism_sepolia_blocks
    batch_flush_interval: "10000"
    append_only_mode: true
    schema_override:
      hash: FixedString(66)
      number: UInt64 CODEC(Delta, ZSTD)
      timestamp: DateTime CODEC(Delta, ZSTD)
    from: optimism_sepolia_blocks
  clickhouse_optimism_sepolia.raw_logs:
    type: clickhouse
    table: op_sepolia_logs
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from optimism_sepolia.raw_logs to optimism_sepolia_logs
    batch_flush_interval: "10000"
    append_only_mode: true
    schema_override:
      address: FixedString(42)
      log_index: UInt64
      block_hash: FixedString(66)
      block_number: UInt64 CODEC(Delta, ZSTD)
      block_timestamp: DateTime CODEC(Delta, ZSTD)
      transaction_hash: FixedString(66)
      transaction_index: UInt64
    from: optimism_sepolia_raw_logs
  clickhouse_optimism_sepolia.transaction_receipts:
    type: clickhouse
    table: op_sepolia_transactions
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from optimism_sepolia.transaction_receipts to
      optimism_sepolia_transactions
    batch_flush_interval: "10000"
    append_only_mode: true
    schema_override:
      gas: UInt128
      hash: FixedString(66)
      nonce: UInt64
      value: UInt256
      gas_price: UInt128
      block_hash: FixedString(66)
      to_address: FixedString(42)
      block_number: UInt64 CODEC(Delta, ZSTD)
      from_address: FixedString(42)
      receipt_l1_fee: Nullable(UInt128)
      receipt_status: UInt8
      block_timestamp: DateTime CODEC(Delta, ZSTD)
      max_fee_per_gas: UInt128
      receipt_gas_used: UInt128
      transaction_type: UInt8
      transaction_index: UInt64
      receipt_l1_gas_used: Nullable(UInt128)
      receipt_l1_gas_price: Nullable(UInt128)
      receipt_l1_fee_scalar: Nullable(Float64)
      receipt_l1_block_number: Nullable(Int64)
      max_priority_fee_per_gas: UInt128
      receipt_l1_blob_base_fee: Nullable(UInt128)
      receipt_l1_base_fee_scalar: Nullable(Float64)
      receipt_cumulative_gas_used: UInt128
      receipt_effective_gas_price: UInt128
      receipt_l1_blob_base_fee_scalar: Nullable(Float64)
    from: optimism_sepolia_transactions
  clickhouse_optimism_sepolia.raw_traces:
    type: clickhouse
    table: op_sepolia_traces
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from optimism_sepolia.raw_traces to traces
    batch_flush_interval: "10000"
    append_only_mode: true
    schema_override:
      gas: UInt128
      value: UInt256
      status: UInt8
      gas_used: UInt128
      subtraces: UInt256
      block_hash: FixedString(66)
      to_address: FixedString(42)
      block_number: UInt64 CODEC(Delta(4), ZSTD)
      from_address: FixedString(42)
      block_timestamp: DateTime CODEC(Delta, ZSTD)
      transaction_hash: FixedString(66)
      transaction_index: UInt64
    from: optimism_sepolia_raw_traces
