apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dagster-secret-provider-class
  namespace: dagster
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/oplabs-tools-data/secrets/op-analytics-python-runner/versions/latestver"
        path: "op-analytics-vault.txt"