name: {chain_name}-{network_name}
resource_size: s
apiVersion: 3
sources:
  {chain_db_name}.raw_blocks:
    dataset_name: {chain_db_name}.raw_blocks
    version: {raw_blocks_version}
    type: dataset
    start_at: earliest
  {chain_db_name}.raw_logs:
    dataset_name: {chain_db_name}.raw_logs
    version: {raw_logs_version}
    type: dataset
    start_at: earliest
  {chain_db_name}.{enriched_transactions_name}:
    dataset_name: {chain_db_name}.{enriched_transactions_name}
    version: {enriched_transactions_version}
    type: dataset
    start_at: earliest
  {chain_db_name}.raw_traces:
    dataset_name: {chain_db_name}.raw_traces
    version: {raw_traces_version}
    type: dataset
    start_at: earliest
transforms:
  {chain_db_name}_blocks:
    primary_key: id
    sql: |
      select
        *
        ,'{chain_name}' as chain
        ,'{network_name}' as network
        ,{chain_id} as chain_id
      from
        {chain_db_name}.raw_blocks
  {chain_db_name}_raw_logs:
    primary_key: id
    sql: |
      select
        *
        ,'{chain_name}' as chain
        ,'{network_name}' as network
        ,{chain_id} as chain_id
      from
        {chain_db_name}.raw_logs
  {chain_db_name}_raw_traces:
    primary_key: id
    sql: |
      select
        *
        ,'{chain_name}' as chain
        ,'{network_name}' as network
        ,{chain_id} as chain_id
      from
        {chain_db_name}.raw_traces
  {chain_db_name}_transactions:
    primary_key: id
    sql: |
      select
         *
        ,'{chain_name}' as chain
        ,'{network_name}' as network
        ,{chain_id} as chain_id
      from
        {chain_db_name}.{enriched_transactions_name}
sinks:
  clickhouse_{chain_db_name}.raw_blocks:
    type: clickhouse
    table: {chain_name}_{network_slug}blocks
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from {chain_db_name}.raw_blocks to {chain_db_name}_blocks
    batch_flush_interval: '10000'
    append_only_mode: true
    schema_override:
      hash: FixedString(66)
      number: UInt64 CODEC(Delta, ZSTD)
      timestamp: DateTime CODEC(Delta, ZSTD)
    from: {chain_db_name}_blocks
  clickhouse_{chain_db_name}.raw_logs:
    type: clickhouse
    table: {chain_name}_{network_slug}logs
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from {chain_db_name}.raw_logs to {chain_db_name}_logs
    batch_flush_interval: '10000'
    append_only_mode: true
    schema_override:
      address: FixedString(42)
      log_index: UInt64
      block_hash: FixedString(66)
      block_number: UInt64 CODEC(Delta, ZSTD)
      block_timestamp: DateTime CODEC(Delta, ZSTD)
      transaction_hash: FixedString(66)
      transaction_index: UInt64
    from: {chain_db_name}_raw_logs
  clickhouse_{chain_db_name}.{enriched_transactions_name}:
    type: clickhouse
    table: {chain_name}_{network_slug}transactions
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: >-
      ClickHouse sink from {chain_db_name}.{enriched_transactions_name} to
      {chain_db_name}_transactions
    batch_flush_interval: '10000'
    append_only_mode: true
    schema_override:
      gas: UInt128
      hash: FixedString(66)
      nonce: UInt64
      value: UInt256
      gas_price: UInt128
      block_hash: FixedString(66)
      to_address: FixedString(42)
      block_number: UInt64 CODEC(Delta, ZSTD)
      from_address: FixedString(42)
      receipt_l1_fee: Nullable(UInt128)
      receipt_status: UInt8
      block_timestamp: DateTime CODEC(Delta, ZSTD)
      max_fee_per_gas: UInt128
      receipt_gas_used: UInt128
      transaction_type: UInt8
      transaction_index: UInt64
      receipt_l1_gas_used: Nullable(UInt128)
      receipt_l1_gas_price: Nullable(UInt128)
      receipt_l1_fee_scalar: Nullable(Float64)
      receipt_l1_block_number: Nullable(Int64)
      max_priority_fee_per_gas: UInt128
      receipt_l1_blob_base_fee: Nullable(UInt128)
      receipt_l1_base_fee_scalar: Nullable(Float64)
      receipt_cumulative_gas_used: UInt128
      receipt_effective_gas_price: UInt128
      receipt_l1_blob_base_fee_scalar: Nullable(Float64)
    from: {chain_db_name}_transactions
  clickhouse_{chain_db_name}.raw_traces:
    type: clickhouse
    table: {chain_name}_{network_slug}traces
    batch_size: 100000
    secret_name: OP_DEMO_CLICKHOUSE
    description: ClickHouse sink from {chain_db_name}.raw_traces to traces
    batch_flush_interval: '10000'
    append_only_mode: true
    schema_override:
      gas: UInt128
      value: UInt256
      status: UInt8
      gas_used: UInt128
      subtraces: UInt256
      block_hash: FixedString(66)
      to_address: FixedString(42)
      block_number: UInt64 CODEC(Delta(4), ZSTD)
      from_address: FixedString(42)
      block_timestamp: DateTime CODEC(Delta, ZSTD)
      transaction_hash: FixedString(66)
      transaction_index: UInt64
    from: {chain_db_name}_raw_traces
