[project]
name = "op-datasets"
version = "0.1.0"
description = "Utilities to index on-chain data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "op-coreutils",
    "pydantic>=2.9.2",
    "pyiceberg>=0.7.1",
    "urllib3>=2.2.3",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
