import typer
from op_analytics.coreutils.logger import structlog


from op_analytics.cli.subcommands.misc.docsgen import schema_mapping_docs

log = structlog.get_logger()

app = typer.Typer(help="Miscelaneous housekeeping utilities.", add_completion=False)


@app.command()
def generate_docs():
    """Autogenerated sphinx docs files."""
    schema_mapping_docs.generate()
