import typer
from op_coreutils.logger import structlog

from op_analytics.cli.subcommands.misc import chain_metadata
from op_analytics.cli.subcommands.misc.dbtgen import (
    dbt_docs,
    goldsky_dbt_sources,
    goldsky_dbt_views,
    superchain_dbt_sources,
)
from op_analytics.cli.subcommands.misc.docsgen import schema_mapping_docs

log = structlog.get_logger()

app = typer.Typer(help="Miscelaneous housekeeping utilities.", add_completion=False)


app.command(name="upload_metadata")(chain_metadata.upload_metadata)
app.command(name="customize_dbt")(dbt_docs.customize)


@app.command()
def generate_dbt():
    """Autogenerated dbt source and model files."""
    goldsky_dbt_sources.generate()
    goldsky_dbt_views.generate()
    superchain_dbt_sources.generate()


@app.command()
def generate_docs():
    """Autogenerated sphinx docs files."""
    schema_mapping_docs.generate()
