name: On-Demand Chain Metadata Updates
run-name: ${{ github.event.created_at }}
on:
  schedule:
    - cron: '5 18 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-daily-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Chain Metadata
        run: uv run opdata chains chain_metadata_updates
        env:
          OPLABS_ENV: prod
          OP_ANALYTICS_VAULT: ${{ secrets.OP_ANALYTICS_VAULT }}

