name: Python Package Installation and Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.11"

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev --skip-lock

    - name: Show dependency graph
      run: pipenv graph

    - name: Check for security vulnerabilities
      run: pipenv check || echo "Pipenv check failed, but continuing workflow"

    - name: Show installed packages
      run: pipenv run pip list

    - name: Check for dependency conflicts
      run: |
        echo "Checking for potential conflicts..."
        pipenv graph | grep -E '\w+==.+\s+\w+==.+' || echo "No obvious conflicts found in dependency graph"
        
        echo "Packages with multiple versions:"
        pipenv graph | awk -F'==' '{print $1}' | sort | uniq -c | sort -nr | awk '$1 > 1 {print $0}'

    - name: Show environment information
      run: |
        pipenv --venv
        pipenv --where
        pipenv --py

    - name: List all installed packages with versions
      run: pipenv run pip freeze
